# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: S3Bucket
variables:
  EnvironmentName: nonprod
  jobs:
      - job:
        steps:
          - task: CloudFormationCreateOrUpdateStack@1
            inputs:
              awsCredentials: 'AWS-Connection-Nonprod'
              regionName: 'eu-central-1'
              stackName: 's3-lambdapackages'
              templateSource: 'file'
              templateFile: 'cfn/s3.yml'
        

            
- stage: Build
  jobs:
      - job:
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.8'
          
          - script: |
              pip install cfn-lint
              cfn-lint *.yml
            workingDirectory: cfn
            displayName: 'cfn-lint'
            continueOnError: true 

          
          - script: |
              python -m pip install flake8
              flake8 CreateMobileImage/CreateMobileImage.py
              flake8 CreateWebImage/CreateWebImage.py
              flake8 CreateThumbnail/CreateThumbnail.py
            workingDirectory: lambdas
            displayName: 'pylint'
            continueOnError: true 
          
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: lambdas/CreateMobileImage/
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: 'CreateMobileImage.zip'
              replaceExistingArchive: true
            displayName: 'Create Lambda Package - CreateMobileImage'
            
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: lambdas/CreateThumbnail/
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: 'CreateThumbnail.zip'
              replaceExistingArchive: true
            displayName: 'Create Lambda Package - CreateThumbnail'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: lambdas/CreateWebImage/
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: 'CreateWebImage.zip'
              replaceExistingArchive: true
            displayName: 'Create Lambda Package - CreateWebImage'
            
          - task: S3Upload@1
            inputs:
              awsCredentials: 'AWS-Connection-Nonprod'
              regionName: 'eu-central-1'
              bucketName: 'lambda-launchpad-packages'
              globExpressions: '*.zip'
            displayName: 'Upload Lambda packages to S3'

- stage: DeployNonProduction
  jobs:
      - job:
        steps:
        - task: CloudFormationCreateOrUpdateStack@1
          inputs:
            awsCredentials: 'AWS-Connection-Nonprod'
            regionName: 'eu-central-1'
            stackName: 'microservices'
            templateSource: 'file'
            templateFile: 'cfn/microservices.yml'
          displayName: 'Deploy Microservices'
        
        - task: S3Upload@1
          inputs:
            awsCredentials: 'AWS-Connection-Nonprod'
            regionName: 'eu-central-1'
            bucketName: 'launchpad-app-bucket'
            globExpressions: 'dummyfile.txt'
            targetFolder: 'uploads'
          displayName: 'Create Uploads folder in S3'

        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-Connection-Nonprod'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'CreateMobileImage'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages'
            s3ObjectKey: 'CreateMobileImage.zip'
          displayName: 'Deploy CreateMobileImage Lambda'
          
        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-Connection-Nonprod'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'CreateThumbnail'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages'
            s3ObjectKey: 'CreateThumbnail.zip'
          displayName: 'Deploy CreateThumbnail Lambda'
          
        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-Connection-Nonprod'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'CreateWebImage'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages'
            s3ObjectKey: 'CreateWebImage.zip'
          displayName: 'Deploy CreateWebImage Lambda'
  
- stage: DeployProduction
  jobs:
      - job:
        steps:
        - task: CloudFormationCreateOrUpdateStack@1
          inputs:
            awsCredentials: 'AWS-Connection-Prod'
            regionName: 'eu-central-1'
            stackName: 'microservices'
            templateSource: 'file'
            templateFile: 'cfn/microservices.yml'
          displayName: 'Deploy Microservices'
        
        - task: S3Upload@1
          inputs:
            awsCredentials: 'AWS-Connection-Prod'
            regionName: 'eu-central-1'
            bucketName: 'launchpad-app-bucket'
            globExpressions: 'dummyfile.txt'
            targetFolder: 'uploads'
          displayName: 'Create Uploads folder in S3'

        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-Connection-Prod'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'CreateMobileImage'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages'
            s3ObjectKey: 'CreateMobileImage.zip'
          displayName: 'Deploy CreateMobileImage Lambda'
          
        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-Connection-Prod'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'CreateThumbnail'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages'
            s3ObjectKey: 'CreateThumbnail.zip'
          displayName: 'Deploy CreateThumbnail Lambda'
          
        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-Connection-Prod'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'CreateWebImage'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages'
            s3ObjectKey: 'CreateWebImage.zip'
          displayName: 'Deploy CreateWebImage Lambda'
