# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: S3Bucket
  jobs:
      - job:
        steps:
          - task: CloudFormationCreateOrUpdateStack@1
            inputs:
              awsCredentials: 'AWS-S3-Connection'
              regionName: 'eu-central-1'
              stackName: 's3-lambdapackages'
              templateSource: 'file'
              templateFile: 'cfn/s3.yml'
            
- stage: Build
  jobs:
      - job:
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.8'
          
          - script: |
              pip install cfn-lint
              cfn-lint *.yml
            workingDirectory: cfn
            displayName: 'cfn-lint'

          
          - script: |
              python -m pip install flake8
              flake8 /**/*.yaml
            workingDirectory: lambdas
            displayName: 'pylint'
          
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'lambdas/CreateMobileImage/*'
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/CreateMobileImage.zip'
              replaceExistingArchive: true
            
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: lambdas/CreateThumbnail/
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/CreateThumbnail.zip'
              replaceExistingArchive: true

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: lambdas/CreateWebImage/
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/CreateWebImage.zip'
              replaceExistingArchive: true
            
          - task: S3Upload@1
            inputs:
              awsCredentials: 'AWS-S3-Connection'
              regionName: 'eu-central-1'
              bucketName: 'lambda-launchpad-packages22'
              sourceFolder: $(Build.ArtifactStagingDirectory)
              globExpressions: '*.zip'

- stage: Deploy
  jobs:
      - job:
        steps:
        - task: CloudFormationCreateOrUpdateStack@1
          inputs:
            awsCredentials: 'AWS-S3-Connection'
            regionName: 'eu-central-1'
            stackName: 'microservices'
            templateSource: 'file'
            templateFile: 'microservices.yml'

        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-S3-Connection'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'CreateMobileImage'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages22'
            s3ObjectKey: 'CreateMobileImage.zip'
          
        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-S3-Connection'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'CreateThumbnail'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages22'
            s3ObjectKey: 'CreateThumbnail.zip'
          
        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-S3-Connection'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'CreateWebImage'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages22'
            s3ObjectKey: 'CreateWebImage.zip'
