# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: S3Bucket
  jobs:
      - job:
        steps:
          - task: CloudFormationCreateOrUpdateStack@1
            inputs:
              awsCredentials: 'AWS-S3-Connection'
              regionName: 'eu-central-1'
              stackName: 's3-lambdapackages'
              templateSource: 'file'
              templateFile: 's3.yml'  
            
- stage: Build
  jobs:
      - job:
        steps:
          - task: CopyFiles@2
            inputs:
              contents: 'lambdas/CreateMobileImage/*'
              targetFolder: $(Build.BinariesDirectory)/CreateMobileImage/
          
          - task: CopyFiles@2
            inputs:
              contents: 'lambdas/CreateThumbnail/*'
              targetFolder: $(Build.BinariesDirectory)/CreateThumbnail/
          
          - task: CopyFiles@2
            inputs:
              contents: 'lambdas/CreateWebImage/*'
              targetFolder: $(Build.BinariesDirectory)/CreateWebImage/
        
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: $(Build.BinariesDirectory)/CreateMobileImage/
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/CreateMobileImage.zip'
              replaceExistingArchive: true
            
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: $(Build.BinariesDirectory)/CreateThumbnail/
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/CreateThumbnail.zip'
              replaceExistingArchive: true

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: $(Build.BinariesDirectory)/CreateWebImage/
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/CreateWebImage.zip'
              replaceExistingArchive: true
            
          - task: S3Upload@1
            inputs:
              awsCredentials: 'AWS-S3-Connection'
              regionName: 'eu-central-1'
              bucketName: 'lambda-launchpad-packages22'
              sourceFolder: $(Build.ArtifactStagingDirectory)/CreateMobileImage/
              globExpressions: '*.zip'
          
          - task: S3Upload@1
            inputs:
              awsCredentials: 'AWS-S3-Connection'
              regionName: 'eu-central-1'
              bucketName: 'lambda-launchpad-packages22'
              sourceFolder: $(Build.ArtifactStagingDirectory)/CreateThumbnail/
              globExpressions: '*.zip'
          
          - task: S3Upload@1
            inputs:
              awsCredentials: 'AWS-S3-Connection'
              regionName: 'eu-central-1'
              bucketName: 'lambda-launchpad-packages22'
              sourceFolder: $(Build.ArtifactStagingDirectory)/CreateWebImage/
              globExpressions: '*.zip'

- stage: Deploy
  jobs:
      - job:
        steps:
        - task: CloudFormationCreateOrUpdateStack@1
          inputs:
            awsCredentials: 'AWS-S3-Connection'
            regionName: 'eu-central-1'
            stackName: 'microservices'
            templateSource: 'file'
            templateFile: 'microservices.yml'

        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-S3-Connection'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'CreateMobileImage'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages22'
            s3ObjectKey: 'CreateMobileImage.zip'
          
        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-S3-Connection'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'CreateThumbnail'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages22'
            s3ObjectKey: 'CreateThumbnail.zip'
          
        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-S3-Connection'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'CreateWebImage'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages22'
            s3ObjectKey: 'CreateWebImage.zip'
