# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: CloudFormationCreateOrUpdateStack@1
    inputs:
      awsCredentials: 'AWS-S3-Connection'
      regionName: 'eu-central-1'
      stackName: 'microservice'
      templateSource: 'file'
      templateFile: 'microservice.yml'
