# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: S3Bucket
  jobs:
      - job:
        steps:
          - task: CloudFormationCreateOrUpdateStack@1
            inputs:
              awsCredentials: 'AWS-S3-Connection'
              regionName: 'eu-central-1'
              stackName: 's3-lambdapackages'
              templateSource: 'file'
              templateFile: 's3.yml'  
            
- stage: Build
  jobs:
      - job:
        steps:
          - task: CopyFiles@2
            inputs:
              contents: 'lambdas/*.zip'
              targetFolder: $(Build.ArtifactStagingDirectory)
              
          - task: S3Upload@1
            inputs:
              awsCredentials: 'AWS-S3-Connection'
              regionName: 'eu-central-1'
              bucketName: 'lambda-launchpad-packages22'
              sourceFolder: $(Build.ArtifactStagingDirectory)
              globExpressions: '$(Build.ArtifactStagingDirectory)/*.zip'

- stage: Deploy
  jobs:
      - job:
        steps:
        - task: CloudFormationCreateOrUpdateStack@1
          inputs:
            awsCredentials: 'AWS-S3-Connection'
            regionName: 'eu-central-1'
            stackName: 'microservices'
            templateSource: 'file'
            templateFile: 'microservices.yml'

        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-S3-Connection'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'photo-resize-1'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages22'
            s3ObjectKey: 'lambda_function.zip'
          
        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-S3-Connection'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'photo-resize-2'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages22'
            s3ObjectKey: 'lambda_function.zip'
          
        - task: LambdaDeployFunction@1
          inputs:
            awsCredentials: 'AWS-S3-Connection'
            regionName: 'eu-central-1'
            deploymentMode: 'codeonly'
            functionName: 'photo-resize-3'
            codeLocation: 's3object'
            s3Bucket: 'lambda-launchpad-packages22'
            s3ObjectKey: 'lambda_function.zip'
