AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation to deploy microservicess

Parameters:
  EnvironmentName:
    Description: The environment the template is being run in. Used for naming resources
    Type: String
    AllowedValues:
      - nonprod
      - preprod
      - prod
  S3BucketName:
    Description: S3 bucket for file upload
    Type: String
    Default: launchpad-app-bucket
  ReplicationBucketName:
    Description: S3 bucket for cross region replication
    Type: String
    Default: launchpad-replica-bucket
  LambdaS3Bucket:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /s3/bucketname
    Description: S3 Bucket Name where Lambda Packages are stored
  RepRegion:
    Type: String
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ca-central-1
      - ap-south-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - sa-east-1
    Default: eu-west-1


Resources:

# S3 bucket for file upload and destination file for resized images
  AppBucket:
    Type: AWS::S3::Bucket
    DependsOn: 
      - TriggerLambda
    Properties:
      BucketName: !Sub "${S3BucketName}-${EnvironmentName}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      ReplicationConfiguration:
        Role: !GetAtt S3Role.Arn
        Rules:
          -
            Destination:
              Bucket: "arn:aws:s3:::dest-bucket-name23456"
                # !Join
                #   - ""
                #   -
                #     - "arn:aws:s3:::"
                #     - !Ref ReplicationBucketName
              StorageClass: STANDARD
            Id: MyRule1
            Prefix: ""
            Status: Enabled
      VersioningConfiguration:
        Status: Enabled

# S3 Cross Region Replication
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      Path: /
      Policies:
        -
          PolicyDocument:
            Statement:
              -
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: Allow
                Resource: "arn:aws:logs:*:*:*"
              -
                Action:
                  - "s3:*"
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
          PolicyName: !Sub "root-${EnvironmentName}"

  ReplicationBucket:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile:
          !Sub |
            var aws = require('aws-sdk');
            var response = require('cfn-response');
            exports.handler = function(event, context, callback){
                var s3 = new aws.S3({region: event.ResourceProperties.DestBucketRegion});
                if (event.RequestType == 'Create' || event.RequestType == 'Update'){
                    var bucketParams = {
                        Bucket: event.ResourceProperties.DestBucketName,
                    };
                    s3.createBucket(bucketParams, function(err, data) {
                        if (err){
                            console.log(err, err.stack)
                            response.send(event, context, response.FAILED, err)
                        }
                        else {
                            console.log(data)
                            var versioningParams = {
                                Bucket: event.ResourceProperties.DestBucketName,
                                VersioningConfiguration: {
                                    Status: 'Enabled'
                                }
                            };
                            s3.putBucketVersioning(versioningParams, function(err, data) {
                                if (err) {
                                    console.log(err, err.stack);
                                }
                                else {
                                    console.log(data)
                                    response.send(event, context, response.SUCCESS, {}, event.destBucketName);
                                    callback(null,'Bucket created!');
                                }
                            });
                        }
                    });
                }
                else if (event.RequestType == 'Delete'){
                    console.log('Please delete the ' + event.PhysicalResourceId + ' bucket.')
                    response.send(event, context, response.SUCCESS, {}, event.PhysicalResourceId);
                    callback(null);
                }
            };
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs14.x
      Timeout: 30
  TriggerLambda:
    Type: Custom::LambdaTrig
    Properties:
      ServiceToken: !GetAtt ReplicationBucket.Arn
      DestBucketName: dest-bucket-name23456
      DestBucketRegion: !Ref RepRegion
  S3Role:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Action: "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        -  arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: /
    Type: "AWS::IAM::Role"